In [1]:
import tensorflow as tf

2024-04-03 15:14:46.611452: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-03 15:14:46.687455: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-03 15:14:47.819634: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


## 基本操作

In [2]:
# 使用 range 创建一个行向量，张量 x 有12个元素
x = tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [3]:
# 可以通过 shape 访问张量的形状
x.shape

TensorShape([12])

In [4]:
# 只检查它的大小
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [5]:
# 改变它的形状
X = tf.reshape(x, (3,4))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [6]:
# 使用常量
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [7]:
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [8]:
tf.random.normal(shape=[3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.3453519 , -0.43310487,  1.7349485 , -0.19463496],
       [-0.9969323 , -1.4889033 ,  1.1503487 , -0.7347622 ],
       [-0.77650386, -0.60183054, -0.20425831, -1.7522733 ]],
      dtype=float32)>

In [9]:
tf.constant([[2,3,4,5],[1,2,3,4],[3,1,4,6]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 3, 4, 5],
       [1, 2, 3, 4],
       [3, 1, 4, 6]], dtype=int32)>

## 运算符

In [10]:
# 加减乘除
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
# ** 是求幂运算
x+y, x-y, x*y, x/y, x**y

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>)

In [11]:
# help(tf.exp)
# Computes exponential of x element-wise.
tf.exp(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
      dtype=float32)>

In [12]:
# concat 多个张量
X = tf.reshape(tf.range(12, dtype=tf.float32), (3,4))
Y = tf.constant([[1,2,3,4],[4,3,2,1],[2.0,1,2,4]])

In [13]:
# axis=0 沿行，轴 0
tf.concat([X,Y], axis=0)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 1.,  2.,  3.,  4.],
       [ 4.,  3.,  2.,  1.],
       [ 2.,  1.,  2.,  4.]], dtype=float32)>

In [14]:
# axis=1 沿列，轴 1
tf.concat([X,Y], axis=1)

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.,  4.,  3.,  2.,  1.],
       [ 8.,  9., 10., 11.,  2.,  1.,  2.,  4.]], dtype=float32)>

In [15]:
X == Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])>

In [16]:
# 对张量中所有元素求和
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

## 广播机制

In [17]:
# 形状不同，可以通过 广播机制 进行按元素操作

In [18]:
a = tf.reshape(tf.range(3), (3,1))
b = tf.reshape(tf.range(2), (1,2))
a,b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

In [19]:
a+b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

## 索引和切片

In [20]:
# 用 -1 选择最后一个元素
X, X[-1]

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>)

In [21]:
# 用 1:3 选择第 2，3个元素 (下标是 1，2)
X[1:3]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [22]:
# 通过索引来写入 Variable 的元素
X_var = tf.Variable(X)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [23]:
X_var[1,2].assign(9)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [24]:
X_var = tf.Variable(X)
X_var[0:2, :].assign(tf.ones(X_var[0:2, :].shape, dtype = tf.float32) * 12)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

## 节省内存

In [25]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [26]:
# Variable 是 tensorflow 中的可变容器，它提供了存储模型参数的方法
Z = tf.Variable(tf.zeros_like(Y))
print("id(z): {}".format(id(Z)))
Z.assign(X + Y)
print("id(z): {}".format(id(Z)))

id(z): 140598245755200
id(z): 140598245755200


In [27]:
# Tensorflow 提供了 tf.function 修饰符，将计算封装在 tensorflow 图中，该图在运行前经过编译和优化

In [28]:
@tf.function
def computation(X, Y):
    Z = tf.zeros_like(Y)   # 这个未使用的值将被删除
    A = X + Y    # 当不再需要时，分配将被复用
    B = A + Y
    C = B + Y
    return C + Y

computation(X, Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 4., 13., 22., 31.],
       [36., 37., 38., 39.],
       [48., 49., 58., 71.]], dtype=float32)>

## 转换为其他 Python 对象

In [29]:
# 将深度学习张量 转为 Numpy 张量
A = X.numpy()
B = tf.constant(A)
type(A), type(B)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

In [30]:
# 将大小为 1 的张量转为标量
a = tf.constant([3.5]).numpy()
a, a.item(), float(a), int(a)

(array([3.5], dtype=float32), 3.5, 3.5, 3)

## 练习

In [35]:
X, Y

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 1.,  3.,  5.,  7.],
        [ 8.,  8.,  8.,  8.],
        [10., 10., 12., 15.]], dtype=float32)>)

In [34]:
X < Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

In [32]:
X > Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [54]:
c = tf.reshape(tf.range(6), (2,1,3))
d = tf.reshape(tf.range(2), (1,2,1))
c, d

(<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
 array([[[0, 1, 2]],
 
        [[3, 4, 5]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 1), dtype=int32, numpy=
 array([[[0],
         [1]]], dtype=int32)>)

In [55]:
c+d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[0, 1, 2],
        [1, 2, 3]],

       [[3, 4, 5],
        [4, 5, 6]]], dtype=int32)>