In [1]:
import tensorflow as tf

2024-04-03 16:21:30.172448: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-03 16:21:30.260322: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-03 16:21:31.503154: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


## 标量

In [4]:
# 仅包含一个数值称为 标量 scalar

In [5]:
x = tf.constant(3.0)
y = tf.constant(2.0)
x+y, x-y, x*y, x/y, x**y

(<tf.Tensor: shape=(), dtype=float32, numpy=5.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.0>)

## 向量

标量值组成的列表称为向量

In [7]:
x = tf.range(4)
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

列向量是向量的默认方向

In [9]:
x[3]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [12]:
# 长度
len(x)

4

In [13]:
# 形状
x.shape

TensorShape([4])

## 矩阵

矩阵把向量丛一阶推到二阶

In [14]:
A = tf.reshape(tf.range(12), (3,4))
A

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [15]:
# 转置矩阵
tf.transpose(A)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]], dtype=int32)>

In [16]:
# 对称矩阵
B = tf.constant([[1,2,3], [2,0,4], [3,4,5]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]], dtype=int32)>

In [18]:
B == tf.transpose(B)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

## 张量

具有任意数量轴的 N 维数组叫做张量

In [19]:
X = tf.reshape(tf.range(24), (2,3,4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

## 张量算法的基本特性

任何按元素二元运算的结果都将是相同形状的张量

In [22]:
A = tf.reshape(tf.range(20, dtype=tf.float32), (5,4))
B = A
A, A+B

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]], dtype=float32)>)

In [23]:
# 两个矩阵的按元素乘法称为 Hadamard 积
A * B

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]], dtype=float32)>

将张量乘以或者加上一个标量不会改变张量的形状

In [28]:
a = 2
X = tf.reshape(tf.range(12), (3,4))
a + X, (a * X).shape

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]], dtype=int32)>,
 TensorShape([3, 4]))

## 降维

In [29]:
# 求和
X = tf.reshape(tf.range(12), (3,4))
X, tf.reduce_sum(X)

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=66>)

默认情况下，调用求和函数 `sum()` 会沿着所有的轴降低张量的维度，使它变成一个标量。  
我们也可以通过指定张量沿着某一个轴来通过求和降低维度。

In [31]:
X_sum_axia0 = tf.reduce_sum(X, axis=0)
X_sum_axia0, X_sum_axia0.shape

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12, 15, 18, 21], dtype=int32)>,
 TensorShape([4]))

In [34]:
# 沿哪个轴降维，哪个轴就从输出形状中消失

X_sum_axia1 = tf.reduce_sum(X, axis=1)
X_sum_axia1, X_sum_axia1.shape

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 22, 38], dtype=int32)>,
 TensorShape([3]))

In [35]:
# 和 tf.reduce_sum(A) 一样
tf.reduce_sum(X, axis=[0,1])

<tf.Tensor: shape=(), dtype=int32, numpy=66>

In [38]:
# 求平均值
tf.reduce_mean(A), tf.reduce_sum(A) / tf.size(A).numpy()

(<tf.Tensor: shape=(), dtype=float32, numpy=9.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.5>)

In [39]:
# 求平均值也可以沿指定轴降低张量的维度
tf.reduce_mean(A, axis=0), tf.reduce_sum(A, axis=0) / A.shape[0]

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>)

In [40]:
A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

### 非降维求和

In [42]:
# 沿着列，对每行求和后，依然保持两个轴
sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
sum_A

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]], dtype=float32)>

In [43]:
A / sum_A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]], dtype=float32)>

In [44]:
# axis=0 按行计算，累积综合
tf.cumsum(A, axis=0)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  6.,  8., 10.],
       [12., 15., 18., 21.],
       [24., 28., 32., 36.],
       [40., 45., 50., 55.]], dtype=float32)>

## 点积

In [48]:
x = tf.range(4, dtype=tf.float32)
y = tf.ones(4, dtype=tf.float32)
x,y

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>)

In [49]:
tf.tensordot(x, y, axes=1)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [50]:
tf.reduce_sum(x * y)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

## 矩阵 - 向量积

In [51]:
A.shape

TensorShape([5, 4])

In [52]:
x.shape

TensorShape([4])

In [54]:
# A 的列维数（沿轴1的长度）必须与 x 的维数（其长度）相同
tf.linalg.matvec(A, x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 14.,  38.,  62.,  86., 110.], dtype=float32)>

## 矩阵 - 矩阵乘法

In [56]:
B = tf.ones((4,3), tf.float32)
tf.matmul(A, B)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]], dtype=float32)>

## 范数

向量的范数是表示一个向量有多大，求平方和开根号

In [58]:
u = tf.constant([3.0, -4.0])
# L2 范数
tf.norm(u)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [59]:
# L1 范数：绝对值函数求和
tf.reduce_sum(tf.abs(u))

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [60]:
# 与 L2 范数相比，L1 范数受异常值的影响较小

In [61]:
# Frobenius 范数
tf.norm(tf.ones((4, 9)))

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

## 练习

In [62]:
# 1. 证明一个矩阵 A 的转置的转置是 A

In [63]:
A1 = tf.reshape(tf.range(12), (3,4))
A1

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [64]:
A1_t = tf.transpose(A1)
tf.transpose(A1_t)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [65]:
# 2. 给出两个矩阵A和B，证明 “它们转置的和” 等于 “它们和的转置”

In [66]:
A = tf.reshape(tf.range(12), (3,4))
B = tf.reshape(tf.range(3), (3,1))
A, B

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>)

In [67]:
tf.transpose(A) + tf.transpose(B) == tf.transpose(A+B)

<tf.Tensor: shape=(4, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [68]:
# 3. 给定任意方阵 A， A + A 的转置 总是对称的吗？为什么？

In [70]:
A, tf.transpose(A)

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]], dtype=int32)>)

In [71]:
# 4. 本节中定义了形状 (2,3,4) 的张量 X。len(X) 的输出结果是什么？

In [72]:
X = tf.reshape(tf.range(24), (2,3,4))
len(X)

2

In [73]:
# 5. 对于任意形状的张量 X，len(X) 是否总是对应于 X特定轴的长度？这个轴是什么？

In [77]:
# 固定输出 轴 0 的长度

In [74]:
# 6. 运行 A/A.sum(axis=1), 看看会发生什么。分析一下原因

In [76]:
A = tf.reshape(tf.range(20, dtype=tf.float32), (5,4))
A / A.sum(axis=1)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'sum'

In [78]:
# 7. 考虑一个具有形状 (2,3,4) 的张量，在轴 0、1、2 上的求和输出是什么形状？

In [79]:
X = tf.ones((2,3,4))
X_0 = tf.reduce_sum(X, axis=0)
X_1 = tf.reduce_sum(X, axis=1)
X_2 = tf.reduce_sum(X, axis=2)
X_0.shape, X_1.shape, X_2.shape

(TensorShape([3, 4]), TensorShape([2, 4]), TensorShape([2, 3]))

In [80]:
# 8. 为linalg.norm函数提供3个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么?

In [83]:
tf.norm(tf.ones((4, 4, 4)))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>